### ISSUE TITLE
What changed

### ISSUE THREAD

**Issue by jayvdb** [SzieberthAdam/jsonfile#1]
Beyond knowing there was a change, the next step is notifications which described what was changed.

**Comment by SzieberthAdam** [comment]
Hello! I am happy that you find this library. ATM it is mainly for my own use. Since then there are changes yet uncommitted as I use this in another project. This version is far from idal. Normally, the API of the containers should be identical with the builtin objects (list, dict). This has been improved but not good enough yet. Once I tested it enough, I might make the code more to the public. However, I push the current version. Again, there will be no details.

**Comment by jayvdb** [comment]
Hiya, thanks for replying.
My interest is how to know what changed in the json.  Currently it only tells the event `on_change` that something was changed, without any info about what changed.

**Comment by SzieberthAdam** [comment]
You should override `may_changed()` then. It has both the old and the new data.

**Comment by jayvdb** [comment]
Thanks!  Some docs for `on_change` and `may_changed` would help potential users ;-)

**Comment by SzieberthAdam** [comment]
As of version 0.1.0 I removed most of the obscure code. This includes the `on_change` and `may_changed` methods. These methods did a full copy of the internal container every time and compared the old and new values. This was very ineffective and had to go.

_The new JSONFile object will rewrite the file every time if autosave is turned on and there is a possibility that the data has been changed._

If you want to know what has been changed, it must be your program which detects that and not this module. I want the module to stay simple. You know, _simple is better than complex_. Thus, what I would do in my program is to figure out a smart way to detect whether the data changes, and only do the method calls if there is a true change. The main program does the change after all, so it should know.

If autosave is on, I recommend `JSONFileArray.extend()` instead of `append()` and `JSONFileObject.update()` instead of setting the key-value pairs one-by-one to avoid multiple rewrites on disk. Alternatively, I would turn off autosave and do manual `JSONFileRoot.save()˙ calls at proper points.

Note that current dump settings are version control friendly which I found very useful to detect bugs in my main program during development. If a previously good data output get screwed up by the new code, the git system showed that for me. If you stick to have JSON compatible types in your data, you can use this module to wrap your internal data during development in order to get a live view on it. Other types are not supported out of the box and never will. However, custom JSON encoder/decoder classes might be in 0.2.0. That makes to serialize those as well like this:

https://stackoverflow.com/questions/12122007/python-json-encoder-to-support-datetime/23361323#23361323

Cheers,
Ádám

**Comment by SzieberthAdam** [comment]
Hah, there is no need for 0.2.0 for that. `dump_kwargs` and `load_kwargs` both have the `cls` key. You can put your custom encoder/decoder class there.
